on:
  push:
  pull_request:
  schedule:
  - cron: "0 * * * *"
env:
  MAZE_REPO: "https://beta.maze-ci.org/mikkeloscar/maze"
  MAZE_TOKEN: ${{ secrets.MAZE_TOKEN }}
jobs:
  build_packages:
    strategy:
      matrix:
        package:
        # - {name: "sway-git"}
        # - {name: "wlroots-git"}
        - {name: "dropbox", signing_keys: "FC918B335044912E"}
        - {name: "google-chrome"}
        - {name: "scaleway-cli"}
        - {name: "google-cloud-sdk"}
        - {name: "pacaur"}
        - {name: "auracle-git"}
        - {name: "virtualbox-ext-oracle"}
        - {name: "xdg-utils-mimeo"}
        - {name: "mimeo"}
        - {name: "chromium-widevine"}
        - {name: "profile-sync-daemon"}
        - {name: "gtk3-optional-csd"}
        - {name: "jdk"}
        - {name: "gtk-theme-arc"}
        - {name: "gtk-theme-arc-git"}
        - {name: "moka-icon-theme-git"}
        # - {name: "android-sdk"}
        # - {name: "android-sdk-build-tools"}
        # - {name: "android-sdk-platform-tools"}
        # - {name: "android-ndk"}
        # - {name: "android-support-repository"}
        # - {name: "android-google-apis"}
        # - {name: "android-google-repository"}
        # - {name: "android-studio"}
        # - {name: "android-sources"}
        - {name: "python-grip-git"}
        - {name: "visual-studio-code-bin"}
        - {name: "kubectl-bin"}
        - {name: "minikube"}
        - {name: "pulseaudio-ctl"}
        # - {name: "upspin-git"}
        - {name: "minikube-bin"}
        # - {name: "mkdocs"}
        - {name: "stern-bin"}
        - {name: "zoom"}
        # - {name: "python-i3-py"}
        - {name: "cni-plugins-bin"}
        - {name: "obs-v4l2sink"}
        # - {name: "aws-sam-cli"}
        - {name: "aws-cli-v2-bin"}
        - {name: "aws-session-manager-plugin"}
        - {name: "kind"}
        - {name: "kubelogin"}
        - {name: "akamai-bin"}
        - {name: "trivy-bin"}
        - {name: "grype-bin"}
        - {name: "crictl-bin"}
        # - {name: "mkdocs-material"}
        # - {name: "mkdocs-material-extensions-git"}
        # - {name: "eksctl"}
    runs-on: ubuntu-latest
    name: Build Maze Packages
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "${{ matrix.package.name }}"
      uses: ./
      with:
        package: "${{ matrix.package.name }}"
        signing_keys: "${{ matrix.package.signing_keys }}"
